# Generated by Django 5.0.7 on 2024-08-30 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0002_alter_propostainvestimento_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostainvestimento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
